services:
  backend:
    image: productlist-backend
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: on-failure

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: productlist
      POSTGRES_USER: tobrod
      POSTGRES_PASSWORD: 1tobrod2
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U tobrod -d productlist" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: on-failure
